languege: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mariofigueira/docker-react -f Dockerfile.dev .

  script:
  - docker run -e CI=true mariofigueira/docker-react npm run test -- --coverage