sudo: required
services:
  - dockerfile

before_install:
  - docker build -t henrir21/docker-react -f Dockerfile.dev .

  script:
  - docker run -e CI=true henrir21/docker-react npm run test -- --coverage