sudo: required
services:
  - dockerfile

before_install:
  - docker build -t mariofigueira/docker-react -f Dockerfile.dev .

  script:
  - docker run mariofigueira/docker-react npm run test -- --coverage